/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ClaimTopicsRegistry: {
      address: "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
          ],
          name: "ClaimTopicAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
          ],
          name: "ClaimTopicRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_claimTopic",
              type: "uint256",
            },
          ],
          name: "addClaimTopic",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getClaimTopics",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_claimTopic",
              type: "uint256",
            },
          ],
          name: "removeClaimTopic",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addClaimTopic: "contracts/registry/interface/IClaimTopicsRegistry.sol",
        getClaimTopics: "contracts/registry/interface/IClaimTopicsRegistry.sol",
        removeClaimTopic:
          "contracts/registry/interface/IClaimTopicsRegistry.sol",
        owner:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        renounceOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        transferOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
      },
    },
    IdentityRegistry: {
      address: "0x959922bE3CAee4b8Cd9a407cc3ac1C251C2007B1",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "claimTopicsRegistry",
              type: "address",
            },
          ],
          name: "ClaimTopicsRegistrySet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint16",
              name: "country",
              type: "uint16",
            },
          ],
          name: "CountryUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "identity",
              type: "address",
            },
          ],
          name: "IdentityRegistered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "identity",
              type: "address",
            },
          ],
          name: "IdentityRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "identityStorage",
              type: "address",
            },
          ],
          name: "IdentityStorageSet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "oldIdentity",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "newIdentity",
              type: "address",
            },
          ],
          name: "IdentityUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "trustedIssuersRegistry",
              type: "address",
            },
          ],
          name: "TrustedIssuersRegistrySet",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "addAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_userAddresses",
              type: "address[]",
            },
            {
              internalType: "contract IIdentity[]",
              name: "_identities",
              type: "address[]",
            },
            {
              internalType: "uint16[]",
              name: "_countries",
              type: "uint16[]",
            },
          ],
          name: "batchRegisterIdentity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "contains",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "deleteIdentity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "identity",
          outputs: [
            {
              internalType: "contract IIdentity",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "identityStorage",
          outputs: [
            {
              internalType: "contract IIdentityRegistryStorage",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trustedIssuersRegistry",
              type: "address",
            },
            {
              internalType: "address",
              name: "_claimTopicsRegistry",
              type: "address",
            },
            {
              internalType: "address",
              name: "_identityStorage",
              type: "address",
            },
          ],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "investorCountry",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "isAgent",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "isVerified",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "issuersRegistry",
          outputs: [
            {
              internalType: "contract ITrustedIssuersRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
            {
              internalType: "uint16",
              name: "_country",
              type: "uint16",
            },
          ],
          name: "registerIdentity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "removeAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_claimTopicsRegistry",
              type: "address",
            },
          ],
          name: "setClaimTopicsRegistry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identityRegistryStorage",
              type: "address",
            },
          ],
          name: "setIdentityRegistryStorage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_trustedIssuersRegistry",
              type: "address",
            },
          ],
          name: "setTrustedIssuersRegistry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "topicsRegistry",
          outputs: [
            {
              internalType: "contract IClaimTopicsRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "uint16",
              name: "_country",
              type: "uint16",
            },
          ],
          name: "updateCountry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
          ],
          name: "updateIdentity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        batchRegisterIdentity:
          "contracts/registry/interface/IIdentityRegistry.sol",
        contains: "contracts/registry/interface/IIdentityRegistry.sol",
        deleteIdentity: "contracts/registry/interface/IIdentityRegistry.sol",
        identity: "contracts/registry/interface/IIdentityRegistry.sol",
        identityStorage: "contracts/registry/interface/IIdentityRegistry.sol",
        investorCountry: "contracts/registry/interface/IIdentityRegistry.sol",
        isVerified: "contracts/registry/interface/IIdentityRegistry.sol",
        issuersRegistry: "contracts/registry/interface/IIdentityRegistry.sol",
        registerIdentity: "contracts/registry/interface/IIdentityRegistry.sol",
        setClaimTopicsRegistry:
          "contracts/registry/interface/IIdentityRegistry.sol",
        setIdentityRegistryStorage:
          "contracts/registry/interface/IIdentityRegistry.sol",
        setTrustedIssuersRegistry:
          "contracts/registry/interface/IIdentityRegistry.sol",
        topicsRegistry: "contracts/registry/interface/IIdentityRegistry.sol",
        updateCountry: "contracts/registry/interface/IIdentityRegistry.sol",
        updateIdentity: "contracts/registry/interface/IIdentityRegistry.sol",
        addAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        isAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        owner: "contracts/roles/AgentRoleUpgradeable.sol",
        removeAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        renounceOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
        transferOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
      },
    },
    IdentityRegistryStorage: {
      address: "0x9A676e781A523b5d0C0e43731313A708CB607508",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint16",
              name: "country",
              type: "uint16",
            },
          ],
          name: "CountryModified",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "oldIdentity",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "newIdentity",
              type: "address",
            },
          ],
          name: "IdentityModified",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "identityRegistry",
              type: "address",
            },
          ],
          name: "IdentityRegistryBound",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "identityRegistry",
              type: "address",
            },
          ],
          name: "IdentityRegistryUnbound",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "identity",
              type: "address",
            },
          ],
          name: "IdentityStored",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "investorAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "contract IIdentity",
              name: "identity",
              type: "address",
            },
          ],
          name: "IdentityUnstored",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "addAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
            {
              internalType: "uint16",
              name: "_country",
              type: "uint16",
            },
          ],
          name: "addIdentityToStorage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identityRegistry",
              type: "address",
            },
          ],
          name: "bindIdentityRegistry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "isAgent",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "linkedIdentityRegistries",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
          ],
          name: "modifyStoredIdentity",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "uint16",
              name: "_country",
              type: "uint16",
            },
          ],
          name: "modifyStoredInvestorCountry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "removeAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "removeIdentityFromStorage",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "storedIdentity",
          outputs: [
            {
              internalType: "contract IIdentity",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "storedInvestorCountry",
          outputs: [
            {
              internalType: "uint16",
              name: "",
              type: "uint16",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identityRegistry",
              type: "address",
            },
          ],
          name: "unbindIdentityRegistry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addIdentityToStorage:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        bindIdentityRegistry:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        linkedIdentityRegistries:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        modifyStoredIdentity:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        modifyStoredInvestorCountry:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        removeIdentityFromStorage:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        storedIdentity:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        storedInvestorCountry:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        unbindIdentityRegistry:
          "contracts/registry/interface/IIdentityRegistryStorage.sol",
        addAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        isAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        owner: "contracts/roles/AgentRoleUpgradeable.sol",
        removeAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        renounceOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
        transferOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
      },
    },
    ModularCompliance: {
      address: "0x68B1D87F95878fE05B998F19b66F4baba5De1aed",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "ModuleAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "target",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes4",
              name: "selector",
              type: "bytes4",
            },
          ],
          name: "ModuleInteraction",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "ModuleRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "TokenBound",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "TokenUnbound",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "addModule",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "bindToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "callData",
              type: "bytes",
            },
            {
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "callModuleFunction",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "canTransfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "created",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "destroyed",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getModules",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTokenBound",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "isModuleBound",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_module",
              type: "address",
            },
          ],
          name: "removeModule",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
          ],
          name: "transferred",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_token",
              type: "address",
            },
          ],
          name: "unbindToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addModule: "contracts/compliance/modular/IModularCompliance.sol",
        bindToken: "contracts/compliance/modular/IModularCompliance.sol",
        callModuleFunction:
          "contracts/compliance/modular/IModularCompliance.sol",
        canTransfer: "contracts/compliance/modular/IModularCompliance.sol",
        created: "contracts/compliance/modular/IModularCompliance.sol",
        destroyed: "contracts/compliance/modular/IModularCompliance.sol",
        getModules: "contracts/compliance/modular/IModularCompliance.sol",
        getTokenBound: "contracts/compliance/modular/IModularCompliance.sol",
        isModuleBound: "contracts/compliance/modular/IModularCompliance.sol",
        removeModule: "contracts/compliance/modular/IModularCompliance.sol",
        transferred: "contracts/compliance/modular/IModularCompliance.sol",
        unbindToken: "contracts/compliance/modular/IModularCompliance.sol",
        owner:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        renounceOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        transferOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
      },
    },
    OnChainIdentity: {
      address: "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
            {
              internalType: "bool",
              name: "_isLibrary",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "Approved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Executed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyRemoved",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "_signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "_uri",
              type: "string",
            },
          ],
          name: "addClaim",
          outputs: [
            {
              internalType: "bytes32",
              name: "claimRequestId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_type",
              type: "uint256",
            },
          ],
          name: "addKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_approve",
              type: "bool",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
          ],
          name: "execute",
          outputs: [
            {
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "getClaim",
          outputs: [
            {
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
          ],
          name: "getClaimIdsByTopic",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "claimIds",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKey",
          outputs: [
            {
              internalType: "uint256[]",
              name: "purposes",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKeyPurposes",
          outputs: [
            {
              internalType: "uint256[]",
              name: "_purposes",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "getKeysByPurpose",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
          ],
          name: "getRecoveredAddress",
          outputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
          ],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "isClaimValid",
          outputs: [
            {
              internalType: "bool",
              name: "claimValid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "keyHasPurpose",
          outputs: [
            {
              internalType: "bool",
              name: "result",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "removeClaim",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "removeKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "version",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addClaim: "@onchain-id/solidity/contracts/Identity.sol",
        addKey: "@onchain-id/solidity/contracts/Identity.sol",
        approve: "@onchain-id/solidity/contracts/Identity.sol",
        execute: "@onchain-id/solidity/contracts/Identity.sol",
        getClaim: "@onchain-id/solidity/contracts/Identity.sol",
        getClaimIdsByTopic: "@onchain-id/solidity/contracts/Identity.sol",
        getKey: "@onchain-id/solidity/contracts/Identity.sol",
        getKeyPurposes: "@onchain-id/solidity/contracts/Identity.sol",
        getKeysByPurpose: "@onchain-id/solidity/contracts/Identity.sol",
        getRecoveredAddress: "@onchain-id/solidity/contracts/Identity.sol",
        initialize: "@onchain-id/solidity/contracts/Identity.sol",
        isClaimValid: "@onchain-id/solidity/contracts/Identity.sol",
        keyHasPurpose: "@onchain-id/solidity/contracts/Identity.sol",
        removeClaim: "@onchain-id/solidity/contracts/Identity.sol",
        removeKey: "@onchain-id/solidity/contracts/Identity.sol",
        version: "@onchain-id/solidity/contracts/Identity.sol",
      },
    },
    Token: {
      address: "0x59b670e9fA9D0A427751Af201D676719a970857b",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              indexed: true,
              internalType: "bool",
              name: "_isFrozen",
              type: "bool",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          name: "AddressFrozen",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "AgentRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_compliance",
              type: "address",
            },
          ],
          name: "ComplianceAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_identityRegistry",
              type: "address",
            },
          ],
          name: "IdentityRegistryAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "Paused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_lostWallet",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_newWallet",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_investorOnchainID",
              type: "address",
            },
          ],
          name: "RecoverySuccess",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "TokensFrozen",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "TokensUnfrozen",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "Unpaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "string",
              name: "_newName",
              type: "string",
            },
            {
              indexed: true,
              internalType: "string",
              name: "_newSymbol",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint8",
              name: "_newDecimals",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "string",
              name: "_newVersion",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "_newOnchainID",
              type: "address",
            },
          ],
          name: "UpdatedTokenInformation",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "addAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "_spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_userAddresses",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchBurn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_fromList",
              type: "address[]",
            },
            {
              internalType: "address[]",
              name: "_toList",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchForcedTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_userAddresses",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchFreezePartialTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_toList",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchMint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_userAddresses",
              type: "address[]",
            },
            {
              internalType: "bool[]",
              name: "_freeze",
              type: "bool[]",
            },
          ],
          name: "batchSetAddressFrozen",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_toList",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address[]",
              name: "_userAddresses",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "_amounts",
              type: "uint256[]",
            },
          ],
          name: "batchUnfreezePartialTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "burn",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "compliance",
          outputs: [
            {
              internalType: "contract IModularCompliance",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_subtractedValue",
              type: "uint256",
            },
          ],
          name: "decreaseAllowance",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "forcedTransfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "freezePartialTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "getFrozenTokens",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "identityRegistry",
          outputs: [
            {
              internalType: "contract IIdentityRegistry",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_addedValue",
              type: "uint256",
            },
          ],
          name: "increaseAllowance",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identityRegistry",
              type: "address",
            },
            {
              internalType: "address",
              name: "_compliance",
              type: "address",
            },
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
            {
              internalType: "string",
              name: "_symbol",
              type: "string",
            },
            {
              internalType: "uint8",
              name: "_decimals",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "_onchainID",
              type: "address",
            },
          ],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "isAgent",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
          ],
          name: "isFrozen",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "onchainID",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "paused",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_lostWallet",
              type: "address",
            },
            {
              internalType: "address",
              name: "_newWallet",
              type: "address",
            },
            {
              internalType: "address",
              name: "_investorOnchainID",
              type: "address",
            },
          ],
          name: "recoveryAddress",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_agent",
              type: "address",
            },
          ],
          name: "removeAgent",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "bool",
              name: "_freeze",
              type: "bool",
            },
          ],
          name: "setAddressFrozen",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_compliance",
              type: "address",
            },
          ],
          name: "setCompliance",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identityRegistry",
              type: "address",
            },
          ],
          name: "setIdentityRegistry",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_name",
              type: "string",
            },
          ],
          name: "setName",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_onchainID",
              type: "address",
            },
          ],
          name: "setOnchainID",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_symbol",
              type: "string",
            },
          ],
          name: "setSymbol",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_from",
              type: "address",
            },
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_userAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_amount",
              type: "uint256",
            },
          ],
          name: "unfreezePartialTokens",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "unpause",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "version",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "contracts/token/IToken.sol",
        approve: "contracts/token/IToken.sol",
        balanceOf: "contracts/token/IToken.sol",
        batchBurn: "contracts/token/IToken.sol",
        batchForcedTransfer: "contracts/token/IToken.sol",
        batchFreezePartialTokens: "contracts/token/IToken.sol",
        batchMint: "contracts/token/IToken.sol",
        batchSetAddressFrozen: "contracts/token/IToken.sol",
        batchTransfer: "contracts/token/IToken.sol",
        batchUnfreezePartialTokens: "contracts/token/IToken.sol",
        burn: "contracts/token/IToken.sol",
        compliance: "contracts/token/IToken.sol",
        decimals: "contracts/token/IToken.sol",
        forcedTransfer: "contracts/token/IToken.sol",
        freezePartialTokens: "contracts/token/IToken.sol",
        getFrozenTokens: "contracts/token/IToken.sol",
        identityRegistry: "contracts/token/IToken.sol",
        isFrozen: "contracts/token/IToken.sol",
        mint: "contracts/token/IToken.sol",
        name: "contracts/token/IToken.sol",
        onchainID: "contracts/token/IToken.sol",
        pause: "contracts/token/IToken.sol",
        paused: "contracts/token/IToken.sol",
        recoveryAddress: "contracts/token/IToken.sol",
        setAddressFrozen: "contracts/token/IToken.sol",
        setCompliance: "contracts/token/IToken.sol",
        setIdentityRegistry: "contracts/token/IToken.sol",
        setName: "contracts/token/IToken.sol",
        setOnchainID: "contracts/token/IToken.sol",
        setSymbol: "contracts/token/IToken.sol",
        symbol: "contracts/token/IToken.sol",
        totalSupply: "contracts/token/IToken.sol",
        transfer: "contracts/token/IToken.sol",
        transferFrom: "contracts/token/IToken.sol",
        unfreezePartialTokens: "contracts/token/IToken.sol",
        unpause: "contracts/token/IToken.sol",
        version: "contracts/token/IToken.sol",
        addAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        isAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        owner: "contracts/roles/AgentRoleUpgradeable.sol",
        removeAgent: "contracts/roles/AgentRoleUpgradeable.sol",
        renounceOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
        transferOwnership: "contracts/roles/AgentRoleUpgradeable.sol",
      },
    },
    TrustedIssuersRegistry: {
      address: "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IClaimIssuer",
              name: "trustedIssuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "claimTopics",
              type: "uint256[]",
            },
          ],
          name: "ClaimTopicsUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "version",
              type: "uint8",
            },
          ],
          name: "Initialized",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IClaimIssuer",
              name: "trustedIssuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256[]",
              name: "claimTopics",
              type: "uint256[]",
            },
          ],
          name: "TrustedIssuerAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "contract IClaimIssuer",
              name: "trustedIssuer",
              type: "address",
            },
          ],
          name: "TrustedIssuerRemoved",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "contract IClaimIssuer",
              name: "_trustedIssuer",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "_claimTopics",
              type: "uint256[]",
            },
          ],
          name: "addTrustedIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IClaimIssuer",
              name: "_trustedIssuer",
              type: "address",
            },
          ],
          name: "getTrustedIssuerClaimTopics",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getTrustedIssuers",
          outputs: [
            {
              internalType: "contract IClaimIssuer[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
          ],
          name: "getTrustedIssuersForClaimTopic",
          outputs: [
            {
              internalType: "contract IClaimIssuer[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_issuer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_claimTopic",
              type: "uint256",
            },
          ],
          name: "hasClaimTopic",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_issuer",
              type: "address",
            },
          ],
          name: "isTrustedIssuer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IClaimIssuer",
              name: "_trustedIssuer",
              type: "address",
            },
          ],
          name: "removeTrustedIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IClaimIssuer",
              name: "_trustedIssuer",
              type: "address",
            },
            {
              internalType: "uint256[]",
              name: "_claimTopics",
              type: "uint256[]",
            },
          ],
          name: "updateIssuerClaimTopics",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addTrustedIssuer:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        getTrustedIssuerClaimTopics:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        getTrustedIssuers:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        getTrustedIssuersForClaimTopic:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        hasClaimTopic:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        isTrustedIssuer:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        removeTrustedIssuer:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        updateIssuerClaimTopics:
          "contracts/registry/interface/ITrustedIssuersRegistry.sol",
        owner:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        renounceOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
        transferOwnership:
          "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
